[package]
name = "merchant-pay"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk = "0.4.2"
alloy-primitives = "0.3.1"
alloy-sol-types = "0.3.1"
hex = "0.4.3"
wee_alloc = "0.4.5"

[features]
export-abi = ["stylus-sdk/export-abi"]

[lib]
crate-type = ["lib", "cdylib"]
